version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_prisma
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: tasks
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mysql_test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: tasks_test
    ports:
      - "3307:3306"  # Different port for test database
volumes:
  mysql_data:
